version: '3.6'
services:
  db:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=hermes
      - POSTGRES_PASSWORD=hermes
  function-registry-api:
    build:
      context: .
      target: production
    ports:
      - '8080:8080'

volumes:
  pgdata:
