version: '3.6'
services:
  db:
    image: postgres:9.4
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=pass

volumes:
  pgdata:
